//REGISTRO DE USUARIOS
export const SIGNUP_START         = 'REGISTRAR_USER_START';
export const SIGNUP_ERROR         = 'SIGNUP_ERROR';
export const SIGNUP_SUCCESS       = 'SIGNUP_SUCCESS';
export const ADD_USER_INFO        = 'ADD_USER_INFO';
//PRATOS RESTAURANTE
export const FETCH_PRATOS_SUCCESS = 'FETCH_PRATOS_SUCCESS';
export const FETCH_PRATOS_FAIL = 'FETCH_PRATOS_FAIL';
//LOGIN
export const SIGNIN_SUCCESS           = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR             = 'SIGNIN_ERROR';
export const AUTH_START               = 'AUTH_START'
export const AUTH_SUCCESS             = 'AUTH_SUCCESS'
export const AUTH_FAIL                = 'AUTH_FAIL'
export const LOADING                  = 'LOADING'
export const ERROR                    = 'ERROR'
export const AUTH_LOGOUT              = 'AUTH_LOGOUT';

//USER
export const FETCH_RESTAURANTE_START     = 'FETCH_RESTAURANTE_START';
export const FETCH_RESTAURANTE_SUCCESS   = 'FETCH_RESTAURANTE_SUCCESS'
export const FETCH_STARS_SUCCESS         = 'FETCH_STARS_SUCCESS';


//PEDIDOS_RESTAURANTE
export const FETCH_PEDIDOS_SUCCESS = 'FETCH_PEDIDOS_SUCCESS';

//CARRINHO
export const ADD_CARRINHO = 'ADD_CARRINHO';
export const REMOVE_CARRINHO = 'REMOVE_CARRINHO';
export const FECHAR_CARRINHO = 'FECHAR_CARRINHO';
export const LIMPAR_CARRINHO = 'LIMPAR_CARRINHO';
//
export const HIDE_TOOLBAR   = 'HIDE_TOOLBAR';
export const SHOW_TOOLBAR   = 'SHOW_TOOLBAR';
export const HIDE_SIDEBAR   = 'HIDE_SIDEBAR';
export const SHOW_SIDEBAR   = 'SHOW_SIDEBAR';



export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'
export const MUDAR_STATUS_PEDIDO = 'MUDAR_STATUS_PEDIDO'
export const REGISTRAR_PEDIDO_SUCCESS = 'REGISTRAR_PEDIDO_SUCCESS'


export const DELETA_PRATO_SUCCESS = 'DELETA_PRATO_SUCCESS';
export const REGISTRAR_PRATO_SUCCESS = 'REGISTRAR_PRATO_SUCCESS';