export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOADING = 'LOADING'
export const ERROR = 'ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'
export const MUDAR_STATUS_PEDIDO = 'MUDAR_STATUS_PEDIDO'
export const REGISTRAR_PEDIDO_SUCCESS = 'REGISTRAR_PEDIDO_SUCCESS'


export const DELETA_PRATO_SUCCESS = 'DELETA_PRATO_SUCCESS';
export const REGISTRAR_PRATO_SUCCESS = 'REGISTRAR_PRATO_SUCCESS';