//REGISTRO DE USUARIOS
export const SIGNUP_START         = 'REGISTRAR_USER_START';
export const SIGNUP_ERROR         = 'SIGNUP_ERROR';
export const SIGNUP_SUCCESS       = 'SIGNUP_SUCCESS';
export const ADD_USER_INFO        = 'ADD_USER_INFO'
//LOGIN
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR   = 'SIGNIN_ERROR';
export const AUTH_START     = 'AUTH_START'
export const AUTH_SUCCESS   = 'AUTH_SUCCESS'
export const AUTH_FAIL      = 'AUTH_FAIL'
export const LOADING        = 'LOADING'
export const ERROR          = 'ERROR'
export const AUTH_LOGOUT    = 'AUTH_LOGOUT';

//
export const HIDE_TOOLBAR   = 'HIDE_TOOLBAR';
export const SHOW_TOOLBAR   = 'SHOW_TOOLBAR';
export const HIDE_SIDEBAR   = 'HIDE_SIDEBAR';
export const SHOW_SIDEBAR   = 'SHOW_SIDEBAR';



export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'
export const MUDAR_STATUS_PEDIDO = 'MUDAR_STATUS_PEDIDO'
export const REGISTRAR_PEDIDO_SUCCESS = 'REGISTRAR_PEDIDO_SUCCESS'


export const DELETA_PRATO_SUCCESS = 'DELETA_PRATO_SUCCESS';
export const REGISTRAR_PRATO_SUCCESS = 'REGISTRAR_PRATO_SUCCESS';